version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_distribuidos
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: lanchonete_db
    ports:
      - "5432:5432"